<h1> NumPy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr [0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

arr = np.arange(0,11)

In [14]:
slice_of_arr = arr[0:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

<strong> When you change a sliced array, that change also occurs in the original array!
        The data is not copied, is just a view of the original array. (Shallow copy)

<h6> Python does that to avoid memory issues with very large arrays

In [29]:
arr_copy = arr.copy() # deep copy

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy[:] = 100

In [27]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2d[2][1]

40

In [39]:
arr_2d[2,1]

40

In [40]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

<h2>Conditional selection:

In [42]:
arr = np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
bool_arr = arr > 5

In [46]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [50]:
arr[bool_arr] # arr[arr>5]

array([ 6,  7,  8,  9, 10])