<h1> Numpy Arrays

<strong>To create NumPy arrays from Python objects ->

In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
mat = np.array(my_mat)

In [9]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<strong> The most commom way of creating NumPy Arrays is using np.arange()

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

<strong>np.zeros() to generate arrays of all 0s

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

<strong> linspace() returns evenly spaced numbers over a specified interval.

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
np.linspace(0,20,20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

<strong> np.eye() to create a identity matrix
    (Mi)

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.8400507 , 0.93403064, 0.9033895 , 0.33697598, 0.90709965])

In [24]:
np.random.rand(5,5)

array([[0.08543952, 0.85569371, 0.18756769, 0.5857585 , 0.44894377],
       [0.50567422, 0.60213944, 0.79182829, 0.46635927, 0.9513028 ],
       [0.62154867, 0.77680067, 0.93492071, 0.23257896, 0.08250847],
       [0.31663459, 0.26289555, 0.7973523 , 0.74789826, 0.73711569],
       [0.76355053, 0.41695854, 0.00101787, 0.91738009, 0.30423833]])

In [25]:
np.random.randn(2)

array([1.21176139, 0.92839669])

In [26]:
np.random.randn(2,4)

array([[ 1.48030207,  0.66768293,  1.22028663,  0.17010927],
       [ 0.57787974, -1.25411114,  0.06980928,  0.19498018]])

In [28]:
np.random.randint(1,100) # random integer between 1 to 100

93

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50 ,10)

In [32]:
ranarr

array([12, 47, 12, 42, 30,  3, 35, 37, 23, 19])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr.max()

47

In [35]:
ranarr.min()

3

In [36]:
ranarr

array([12, 47, 12, 42, 30,  3, 35, 37, 23, 19])

In [38]:
ranarr.argmax() # returns the index location of the max value

1

In [39]:
ranarr.argmin()

5

In [40]:
arr.shape

(25,)

In [41]:
arr = arr.reshape(5,5)

In [42]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int32')

In [45]:
from numpy.random import randint

In [46]:
randint(2,10)

8